export const FormActions = {
  VIEW: "View",
  ADD: "Add",
  EDIT: "Edit",
  DELETE: "Delete",
  CLOSE: "Close",
  CHANGE: "Change"
}

export const UILabels = {
  ID: "Id",
  CODE: "Code",
  NAME: "Name",
  PASSWORD: "Password",
  VCODE: "Vender Code",
  VNAME: "Vender Name",
  CNAME: "Name",
  CMOBILE: "Mobile",
  CADDRESS: "Address",
  CCITY: "City",
  CPIN: "PIN",
  CSTATE: "State",
  CFAX: "FAX",
  CTELEPHONE: "Telephone",
  CEMAIL: "Email",
  CWEBSITE: "Website",
  OCSTNO: "CST No",
  OMSTNO: "MST No",
  OTINNO: "TIN No",
  OPAN: "PAN",
  OSERVICETAXNO: "Service Tax No",
  OEXCISEREGNO: "Excise Reg No",
  BNAME: "Bank Name",
  BACCOUNTNO: "Account No",
  BIFSCCODE: "IFSC Code",
  TYPE: "Type",
  DEPRICIATION: "Depriciation Percentage",
  ASSET_NAME: "Asset Name",
  ASSET_TYPE: "Asset Type",
  PRODUCT_SERIAL_NO: "Product Serial No",
  VENDOR_CODE: "Vendor Code",
  COST: "Cost",
  BRANCH: "Branch",
  DATE: "Date",
  FROM_BRANCH: "From Branch",
  TO_BRANCH: "To Branch",
  PROBLEM: "Problem",
  NEW_PART: "New Part",
  SERVICE_NAME: "Service Name",
  VENUE: "Venue",
  INWORD_DATE: "Inword Date",
  OUTWORD_DATE: "Outword Date",
  REASON: "Reason",
  BRANCHMANAGER:"Branch Manager",
  USERNAME:"Username",
  ISVERIFIED:"verifed",
  PRODUCT_NAME: "Product Name",
  QUANTITY: "Quantity",
  DELIVERY_DATE: "Expected Delivery Date"
};

export const UILabelServerMapping = {
  ID: "id",
  CODE: "code",
  NAME: "name",
  PASSWORD: "password",
  VCODE: "vCode",
  VNAME: "vName",
  CNAME: "cName",
  CMOBILE: "cMobile",
  CADDRESS: "cAddress",
  CCITY: "cCity",
  CPIN: "cPIN",
  CSTATE: "cState",
  CFAX: "cFAX",
  CTELEPHONE: "cTelephone",
  CEMAIL: "cEmail",
  CWEBSITE: "cWebsite",
  OCSTNO: "oCSTNo",
  OMSTNO: "oMSTNo",
  OTINNO: "oTINNo",
  OPAN: "oPAN",
  OSERVICETAXNO: "oServiceTaxNo",
  OEXCISEREGNO: "oExciseRegNo",
  BNAME: "bName",
  BACCOUNTNO: "bAccountNo",
  BIFSCCODE: "bIFSCCode",
  TYPE: "type",
  DEPRICIATION: "depriciation",
  ASSET_NAME: "assetName",
  ASSET_TYPE: "assetType",
  PRODUCT_SERIAL_NO: "productSerialNo",
  VENDOR_CODE: "vendorCode",
  COST: "cost",
  BRANCH: "branch",
  DATE: "date",
  FROM_BRANCH: "fromBranch",
  TO_BRANCH: "toBranch",
  PROBLEM: "problem",
  NEW_PART: "newPart",
  SERVICE_NAME: "serviceName",
  VENUE: "venue",
  INWORD_DATE: "inwordDate",
  OUTWORD_DATE: "outwordDate",
  REASON: "reason",
  BRANCHMANAGER:"branchManager",
  USERNAME:"userName",
  ISVERIFIED:"verified",
  PRODUCT_NAME: "productName",
  QUANTITY: "quantity",
  DELIVERY_DATE: "deliveryDate"
}